"""Framework-independent terminology annotation models."""

from .annotations import (
    AnnotationCandidate,
    AnnotationDescriptor,
    AnnotationDescriptorOccurrence,
    AnnotationDetail,
    AnnotationMatcher,
    AnnotationOccurrence,
    AnnotationSummary,
    CollectionCollaborator,
    CollectionMetadata,
    CollectionTerminology,
    ContextResolutionPolicy,
    EntitySetProvenance,
    GatewayContext,
    InterviewAnswer,
    PageAnnotationDescriptors,
    PageAnnotations,
    PresentationDescriptor,
    PresentationPolicy,
    ProjectAnnotations,
    QuestionContext,
    ResolvedMetadata,
    ResourceReference,
)

__all__ = [
    'AnnotationCandidate',
    'AnnotationDescriptor',
    'AnnotationDescriptorOccurrence',
    'AnnotationDetail',
    'AnnotationMatcher',
    'AnnotationOccurrence',
    'AnnotationSummary',
    'CollectionCollaborator',
    'CollectionMetadata',
    'CollectionTerminology',
    'ContextResolutionPolicy',
    'EntitySetProvenance',
    'GatewayContext',
    'InterviewAnswer',
    'PageAnnotationDescriptors',
    'PageAnnotations',
    'PresentationDescriptor',
    'PresentationPolicy',
    'ProjectAnnotations',
    'QuestionContext',
    'ResolvedMetadata',
    'ResourceReference',
]
